name: Deploy to Firebase

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Node.js setup
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Cache dependencies
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          .cache
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Install dependencies
    - name: Install dependencies
      run: |
        npm install
        if [ -d "src/functions" ]; then cd src/functions && npm install && cd ../..; fi

    # Install Firebase Tools
    - name: Install Firebase Tools
      run: npm install -g firebase-tools

    # Build step
    - name: Build
      run: npm run build

    # Deployment
    - name: Deploy to Firebase
      run: |
        firebase deploy \
          --project ${{ vars.FIREBASE_PROJECT }} \
          --only hosting,functions \
          --token ${{ secrets.FIREBASE_TOKEN }} \
          --non-interactive || ( \
            echo "Deployment failed. Retrying with debug output..." && \
            firebase deploy \
              --project ${{ vars.FIREBASE_PROJECT }} \
              --only hosting,functions \
              --token ${{ secrets.FIREBASE_TOKEN }} \
              --non-interactive \
              --debug > firebase-debug.log 2>&1 && \
            echo "--- DEBUG LOG START ---" && \
            cat firebase-debug.log && \
            echo "--- DEBUG LOG END ---" && \
            exit 1 \
          )
