name: Deploy to Firebase
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Root Dependencies
        run: npm install
      - name: Install Function Dependencies
        run: cd src/functions && npm install
      - name: Build Next.js App
        run: npm run build
      - name: Install Firebase Tools
        run: npm install -g firebase-tools@11.8.0
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SA_KEY }}'
          channelId: live
          entryPoint: .
          target: commerceai